name: Deploy Production Env

on:
  release:
    types:
      - published

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGE_HOST }}
          username: ${{ secrets.STAGE_USERNAME }}
          password: ${{ secrets.STAGE_PASSWORD }}
          port: ${{ secrets.STAGE_PORT }}
          script: cd /var/www/manager.vortechstudio.fr && sudo sh update-production.sh
