name: Deploy Production Env

on:
  release:
    types:
      - published

jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd /www/wwwroot/manager.vortechstudio.fr && sudo sh update-production.sh
