name: Deployment

on:
  workflow_dispatch:


jobs:
  on_push_master:
    runs-on: ubuntu-latest
    steps:
      - name: Appel du webhook
        if: github.event_name == 'push'
        run: curl -k -X POST ${{ secrets.WEBHOOK_STAGING }}

  on_publish_release:
    runs-on: ubuntu-latest
    steps:
      - name: Appel du webhook
        if: github.event_name == 'release'
        run: curl -k -X POST ${{ secrets.WEBHOOK_PRODUCTION }}
